### ISSUE TITLE
Dropbox icon blinks while syncing

### ISSUE THREAD

**Issue by and3k** [shiznix/unity-gentoo#110] opened 2015-04-06 20:46 UTC
Hi!

When Dropbox is syncing, the Dropbox/Sync indicator blinks, i.e. it vanishes and then reappears relatedly.

Any suggestions on how to debug?

Thanks!
Bela

**Comment by shiznix** [comment] 2015-04-08 03:11
Hey Bela,
I don't think we install a dropbox indicator from the overlay.
Maybe you are seeing it's systray icon ?

Do you see anything relevant info show up in syslog when syncing ?

**Comment by and3k** [comment] 2015-04-08 05:37
Hi,

yes, it could be a systray icon. But it is unity-themed, but maybe that’s Dropbox doing that itself.

An example of the Dropbox icon: http://itsfoss.itsfoss.netdna-cdn.com/wp-content/uploads/2013/10/Ubuntu_Missing_dropbox_icon.png

journald gives me no messages related to Dropbox…

In Ubuntu, that icon doesn’t blink. But could also be the Dropbox ebuild’s fault somehow?

Thanks

**Comment by shiznix** [comment] 2015-04-09 01:15
Yes, probably themed by the default Unity icon theme (ubuntu-mono-dark) from x11-themes/ubuntu-themes package.

A couple of things Ubuntu may be doing to get around the icon blinking/disappearing.
1. Using the latest version of nautilus-dropbox-2.10.0 (Gentoo still using 1.6.2)
2. Custom patching the nautilus-dropbox source
3. A combination of both 1. and 2.

**Comment by and3k** [comment] 2015-04-09 05:31
OK.

I requested a version bump of  gnome-extra/nautilus-dropbox
https://bugs.gentoo.org/show_bug.cgi?id=546024

Let’s see if that helps :)

**Comment by grray** [comment] 2016-01-22 14:53
Same issue here, also for "psensor" indicator when alarm is going. Looks like bug in unity.

**Comment by shiznix** [comment] 2016-01-26 00:31
Unfortunately I can't test this because Dropbox doesn't work.
They've broken version control for Linux again :(

Dropbox gets stuck in a loop with "You're using an old version of Dropbox. Please download the latest version at www.dropbox.com/downloading".
(see https://bugs.gentoo.org/show_bug.cgi?id=566280)

**Comment by shiznix** [comment] 2016-01-30 11:12
Finally got a working version of dropbox installed (new version 3.12.6 now in portage tree) and can reproduce the icon disappearing/reappearing when syncing.

The problem seems to occur when it tries to animate the icon by displaying dropboxstatus-busy.svg and then dropboxstatus-busy2.svg.
Instead of displaying dropboxstatus-busy2.svg, the icon disappears totally.
So it would appear it cannot draw or display dropboxstatus-busy2.svg image correctly for some reason.

Other animated icons in Gentoo under Unity do work ok.
Barracuda's Copy indicator animates fine when it syncs for example, or nm-applet as another example.
So yes all signs point to a problem with Dropbox or the way we install it on Gentoo.

Another problem I found with the latest Dropbox is that it now uses QT5 and won't launch in a Unity session unless the QT_QPA_PLATFORMTHEME env variable is unset (normally set to 'appmenu-qt5').
So needs to be launched like so 'QT_QPA_PLATFORMTHEME= dropbox' otherwise the following error and hang occurs:
(nautilus): Gtk-CRITICAL **: gtk_icon_theme_get_for_screen: assertion 'GDK_IS_SCREEN (screen)' failed
(nautilus): GLib-GObject-WARNING **: invalid (NULL) pointer instance
(nautilus): GLib-GObject-CRITICAL **: g_signal_connect_object: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed

This however is only needed in Gentoo and not in Ubuntu.
So yeah Dropbox is a bit of a mess at the moment :|

I am unable to reproduce any similar problem with the psensor indicator as mentioned.

**Comment by shiznix** [comment] 2016-01-31 23:06
Think this should be fixed in commit 25c6d97dd22d1a9bdb5fabdd28679449fa946fad
Can you please sync up and test.

Problem was introduced by a patch I committed some time back to fix some SNI systray icon problems with icon/menus not showing at all (mostly for Quassel and Ktorrent but possibly afffects others?).

Those old problems are still there so I've simply improved the patch to fix this bug.
It also has the unexpected bonus of the Quassel icon now colouring itself red when a notification is raised :)

**Comment by and3k** [comment] 2016-02-01 07:00
That worked. Thank you! :)

**Closed** 2016-02-01 11:57 UTC
