### ISSUE TITLE
unity-base/compiz-0.9.12.1_p0_p01_p2015041001 build failure

### ISSUE THREAD

**Issue by and3k** [shiznix/unity-gentoo#112] opened 2015-04-27 18:59 UTC
Hi!

I upgraded to vivid and everything build fine, with the exception of compiz (and I guess therefore unity).

Infos: https://gist.github.com/and3k/7094630c1c4fd353b9c6

Thanks!
Bela

**Comment by shiznix** [comment] 2015-04-27 23:11
Hi and3k,

Can you try to re-emerge with MAKEOPTS=-j1 and report back.

I've seen similar emerge errors where the parallel generating of make files early on in the piece can get a little out of step with each other.

Thanks.

**Comment by and3k** [comment] 2015-04-28 05:33
Hi,

tried it, didn’t help, build log here: https://gist.github.com/and3k/7094630c1c4fd353b9c6

Thanks!

**Comment by shiznix** [comment] 2015-04-28 10:09
The error is caused by >=cmake-3.2

Will implement a fix shortly but for now you should be able to get things back on track by downgrading your cmake version to something <=cmake-3.1

Thanks for finding this, I was already using cmake-2.8 because of other build problems caused by >=cmake-3.0 for mir-base/mir so completely missed it.

**Comment by shiznix** [comment] 2015-04-28 10:44
Should be fixed in commit 2c935453d10296c8a08f6c3a7079c65d0841dcc6

**Closed by shiznix** 2015-04-28 10:44 UTC

**Comment by and3k** [comment] 2015-04-28 15:47
Yes, that fixed it! Can confirm now that vivid works now on `~amd64`.

Thanks for the quick fix! It’s appreciated!
