### ISSUE TITLE
Keyboard layout not change

### ISSUE THREAD

**Issue by xSQL** [shiznix/unity-gentoo#126] opened 2015-12-17 07:48 UTC
This error occurs when you use lightdm or slim (other Display Manager not testing), but when use gdm or "XSESSION=unity startx" error is missing.

**Comment by shiznix** [comment] 2015-12-17 08:49
What's the error?

**Comment by xSQL** [comment] 2015-12-17 09:08
Keyboard layout not change

**Comment by shiznix** [comment] 2015-12-17 09:10
How are you changing the keyboard layout?

**Comment by xSQL** [comment] 2015-12-17 09:14
Ctrl+Alt (set in setting). This shortcut change language mark on the panel, but input text always is English. I think trouble in some init-script of LightDM etc.

**Comment by shiznix** [comment] 2015-12-17 09:19
Thanks, will try to reproduce.

Hopefully because it already works in a 'startx' session it shouldn't be too hard tracking down why it doesn't work in lightdm or slim started session.

**Comment by shiznix** [comment] 2015-12-19 08:22
Have committed a fix, can you please sync up, test and report - thanks :)

**Comment by shiznix** [comment] 2015-12-19 09:38
Should be fixed in commit b3204e16ee471aa3cccfd8a5a1a113571cf61b50

Can you please sync, update, test and report?
Thanks :)

**Comment by xSQL** [comment] 2015-12-19 09:47
Yes. One moment.

**Comment by xSQL** [comment] 2015-12-19 09:49
gentoo systemd[1]: lightdm.service: main process exited, code=ex
gentoo systemd[1]: Failed to start Light Display Manager.

**Comment by xSQL** [comment] 2015-12-19 10:06
I do next:
layman -S
emerge --update xorg-server
emerge --update lightdm

**Comment by xSQL** [comment] 2015-12-19 10:10
gentoo xsql # systemctl -l status lightdm
● lightdm.service - Light Display Manager
   Loaded: loaded (/usr/lib64/systemd/system/lightdm.service; enabled; vendor preset: enabled)
   Active: failed (Result: start-limit) since Сб 2015-12-19 12:01:46 ; 6min ago
     Docs: man:lightdm(1)
  Process: 1805 ExecStart=/usr/sbin/lightdm (code=exited, status=1/FAILURE)
 Main PID: 1805 (code=exited, status=1/FAILURE)
   CGroup: /system.slice/lightdm.service

дек 19 12:01:46 gentoo systemd[1]: lightdm.service holdoff time over, scheduling restart.
дек 19 12:01:46 gentoo systemd[1]: Stopping Light Display Manager...
дек 19 12:01:46 gentoo systemd[1]: Starting Light Display Manager...
дек 19 12:01:46 gentoo systemd[1]: start request repeated too quickly for lightdm.service
дек 19 12:01:46 gentoo systemd[1]: Failed to start Light Display Manager.
дек 19 12:01:46 gentoo systemd[1]: Unit lightdm.service entered failed state.
дек 19 12:01:46 gentoo systemd[1]: lightdm.service failed.

**Comment by susman** [comment] 2015-12-19 10:12
FIxed for me

**Comment by xSQL** [comment] 2015-12-19 10:13
WTF? Maybe bug in my side. Now checking all.

**Comment by shiznix** [comment] 2015-12-20 08:34
Susman, thanks glad it works :)

Any joy xSQL?

**Comment by xSQL** [comment] 2015-12-20 09:24
Still does not work

**Comment by shiznix** [comment] 2015-12-20 09:41
Weird, nothing has changed wrt lightdm in the overlay except for an ebuild log message.

Anything interesting show up in lightdm's logs?
/var/log/lightdm/x-0-greeter.log for instance...

**Comment by shiznix** [comment] 2015-12-21 08:25
Oops xSQL.
When you say that it still does not work, do you mean keyboard layout still does not work or do you mean that you are still getting that error with lightdm?

**Comment by xSQL** [comment] 2015-12-21 09:17
Trouble with strarting LightDM

**Comment by shiznix** [comment] 2015-12-21 20:38
OK, really need a pastebin of those lightdm logs when it fails to start.

But some other things to also check.
Have you perhaps enabled the 'mir' useflag? (Mir is known to not work at all yet, even in Ubuntu)
Have you done an 'etc-update' since emerging the overlay's lightdm?
Check that a lightdm greeter has been selected with 'eselect lightdm list'.
If there is one already selected, then try selecting a different one (lightdm-gtk-greeter for example).

**Comment by xSQL** [comment] 2015-12-21 21:05
No. Mir not in USE. Tomorrow test with mir (in my country now night)

**Comment by xSQL** [comment] 2015-12-21 21:06
I done re-emerge

**Comment by shiznix** [comment] 2015-12-21 21:11
You'll not want to test with mir, make sure you don't have it enabled.
Enabling mir will cause more problems for you.
We just needed to ensure mir was not enabled which would cause lightdm to not start.

**Comment by shiznix** [comment] 2015-12-22 21:19
OK I'll close this keyboard layout issue as fixed then.
Feel free to open a new issue with logs and details about lightdm not starting.

**Closed by shiznix** 2015-12-22 21:19 UTC
