### ISSUE TITLE
unity-base/unity skipped due to unsatisfied dependencies

### ISSUE THREAD

**Issue by susman** [shiznix/unity-gentoo#134] opened 2016-02-25 11:27 UTC
I just noticed I can't get any updates from this overlay, running `emerge -uDNavt @world` results in:
```
!!! The following update(s) have been skipped due to unsatisfied dependencies
!!! triggered by backtracking:

unity-base/unity:0
```

Couldn't find a way to trace it back.

**Comment by shiznix** [comment] 2016-02-26 10:31
Best way to trace this is to version specifically emerge the package and see what complains:
emerge -p =unity-7.3.3_p0_p01_p20151203-r1

That said I have a feeling it could be caused by the DEPEND="<dev-libs/libsigc++-2.6:2" in unity-base/unity and the recent portage tree stabilising dev-libs/libsigc++-2.6.2 a few days ago.

If that's the case, then this should be fixed in commit 827a0846f7ab6740ee5b0addfe28ee1458c55df4

**Comment by susman** [comment] 2016-02-26 10:32
Indeed it seems to be fixed, running upgrade now

**Comment by shiznix** [comment] 2016-02-26 10:46
Closing now, thanks for reporting :)

**Closed by shiznix** 2016-02-26 10:46 UTC
