### ISSUE TITLE
unity-base/unity-7.3.2_p0_p01_p20151016 build failure

### ISSUE THREAD

**Issue by and3k** [shiznix/unity-gentoo#130] opened 2016-01-10 12:19 UTC
I wanted to rebuild unity, but I’ve got this build error:

https://gist.githubusercontent.com/and3k/0dedd12c9633aa7aaca2/raw/3b0a03d060d7c78aaa00e29f52721b823569cb4a/unity-7.3.2_p0_p01_p20151016_build_log

Thanks!
Bela

emerge --info:

```
Portage 2.2.26 (python 3.5.1-final-0, default/linux/amd64/13.0, gcc-5.3.0, glibc-2.22-r1, 3.18.2-gentoo-bela x86_64)
=================================================================
                         System Settings
=================================================================
System uname: Linux-3.18.2-gentoo-bela-x86_64-Intel-R-_Core-TM-_i7-4771_CPU_@_3.50GHz-with-gentoo-2.2
KiB Mem:    32624796 total,  27846968 free
KiB Swap:   35839996 total,  35839996 free
Timestamp of repository gentoo: Sat, 09 Jan 2016 21:30:01 +0000
sh bash 4.3_p42-r1
ld GNU ld (Gentoo 2.25.1 p1.1) 2.25.1
app-shells/bash:          4.3_p42-r1::gentoo
dev-java/java-config:     2.2.0::gentoo
dev-lang/perl:            5.22.1::gentoo
dev-lang/python:          2.7.11-r2::gentoo, 3.3.5-r7::gentoo, 3.4.3-r7::gentoo, 3.5.1-r2::gentoo
dev-util/cmake:           3.4.1::gentoo
dev-util/pkgconfig:       0.28-r3::gentoo
sys-apps/baselayout:      2.2::gentoo
sys-apps/openrc:          0.19.1::gentoo
sys-apps/sandbox:         2.10-r1::gentoo
sys-devel/autoconf:       2.13::gentoo, 2.69-r1::gentoo
sys-devel/automake:       1.11.6-r2::gentoo, 1.12.6-r1::gentoo, 1.13.4-r1::gentoo, 1.14.1-r1::gentoo, 1.15-r1::gentoo
sys-devel/binutils:       2.25.1-r1::gentoo
sys-devel/gcc:            5.3.0::gentoo
sys-devel/gcc-config:     1.8::gentoo
sys-devel/libtool:        2.4.6-r1::gentoo
sys-devel/make:           4.1-r1::gentoo
sys-kernel/linux-headers: 4.3::gentoo (virtual/os-headers)
sys-libs/glibc:           2.22-r1::gentoo
Repositories:

gentoo
    location: /usr/portage
    sync-type: rsync
    sync-uri: rsync://rsync.gentoo.org/gentoo-portage
    priority: -1000

haskell
    location: /var/lib/layman/haskell
    sync-type: laymansync
    sync-uri: git://github.com/gentoo-haskell/gentoo-haskell.git
    masters: gentoo
    priority: 50

jorgicio
    location: /var/lib/layman/jorgicio
    sync-type: laymansync
    sync-uri: https://github.com/jorgicio/jorgicio-gentoo.git
    masters: gentoo
    priority: 50

science
    location: /var/lib/layman/science
    sync-type: laymansync
    sync-uri: git://anongit.gentoo.org/proj/sci.git
    masters: gentoo
    priority: 50

unity-gentoo
    location: /var/lib/layman/unity-gentoo
    sync-type: laymansync
    sync-uri: git://github.com/shiznix/unity-gentoo.git
    masters: gentoo
    priority: 50

and3k-sunrise
    location: /var/lib/overlays/and3k-sunrise
    masters: gentoo
    priority: 9999

ACCEPT_KEYWORDS="amd64 ~amd64"
ACCEPT_LICENSE="*"
CBUILD="x86_64-pc-linux-gnu"
CFLAGS="-march=native -O2 -pipe"
CHOST="x86_64-pc-linux-gnu"
CONFIG_PROTECT="/etc /usr/share/config /usr/share/gnupg/qualified.txt"
CONFIG_PROTECT_MASK="/etc/ca-certificates.conf /etc/dconf /etc/env.d /etc/fonts/fonts.conf /etc/gconf /etc/gentoo-release /etc/revdep-rebuild /etc/sandbox.d /etc/terminfo /etc/texmf/language.dat.d /etc/texmf/language.def.d /etc/texmf/updmap.d /etc/texmf/web2c"
CXXFLAGS="-march=native -O2 -pipe"
DISTDIR="/usr/portage/distfiles"
EMERGE_DEFAULT_OPTS="--jobs --load-average 8 --autounmask n"
FCFLAGS="-O2 -pipe"
FEATURES="assume-digests binpkg-logs config-protect-if-modified distlocks ebuild-locks fixlafiles merge-sync news parallel-fetch preserve-libs protect-owned sandbox sfperms strict unknown-features-warn unmerge-logs unmerge-orphans userfetch userpriv usersandbox usersync xattr"
FFLAGS="-O2 -pipe"
GENTOO_MIRRORS="http://distfiles.gentoo.org"
LANG="en_GB.utf8"
LDFLAGS="-Wl,-O1 -Wl,--as-needed"
MAKEOPTS="-j8 -l8"
PKGDIR="/usr/portage/packages"
PORTAGE_CONFIGROOT="/"
PORTAGE_RSYNC_OPTS="--recursive --links --safe-links --perms --times --omit-dir-times --compress --force --whole-file --delete --stats --human-readable --timeout=180 --exclude=/distfiles --exclude=/local --exclude=/packages"
PORTAGE_TMPDIR="/var/tmp"
USE="X a52 aac acl acpi alsa amd64 autoipd avahi ayatana bash-completion berkdb bidi blas blast bluetooth bookmarks branding bzip2 cairo cdda cjk clang cli colord conductor contrib cracklib crypt cups cxx dbus declarative dri dts dvd dvdr ebook eds emboss encode equalizer evo exif expat fam ffmpeg firefox flac fortran frei0r gcj gdbm gif glamor gnome gnome-keyring gnome-online-accounts gpg gpm gstreamer gtk hdf5 iconv icu inotify introspection ipv6 java jpeg kdenlive lapack lcms ldap libnotify libsecret mad matplotlib mdnsresponder-compat melt mmx mmxext mng modules mp3 mp4 mpeg multilib nautilus nbconvert ncurses networkmanager nls notebook nptl ntfs ogg opengl openmp pam pango parcheck pcre pdf png policykit postproc ppds printsupport pulseaudio python qt3support qt4 qt5 readline sdl seccomp semantic-desktop session spell sse sse2 sse3 sse4_1 ssl ssse3 staging startup-notification svg sync-plugin-portage systemd tcpd test-programs theora tiff tinfo truetype tty-helpers udev udisks unicode upnp upower usb utils v4l vaapi video vorbis webkit widgets wifi wmf wxwidgets x264 xattr xcb xetex xkb xml xmp xv xvfb xvid zeitgeist zeroconf zlib" ABI_X86="64 32" ALSA_CARDS="ali5451 als4000 atiixp atiixp-modem bt87x ca0106 cmipci emu10k1x ens1370 ens1371 es1938 es1968 fm801 hda-intel intel8x0 intel8x0m maestro3 trident usb-audio via82xx via82xx-modem ymfpci" APACHE2_MODULES="authn_core authz_core socache_shmcb unixd actions alias auth_basic authn_alias authn_anon authn_dbm authn_default authn_file authz_dbm authz_default authz_groupfile authz_host authz_owner authz_user autoindex cache cgi cgid dav dav_fs dav_lock deflate dir disk_cache env expires ext_filter file_cache filter headers include info log_config logio mem_cache mime mime_magic negotiation rewrite setenvif speling status unique_id userdir usertrack vhost_alias" CALLIGRA_FEATURES="kexi words flow plan sheets stage tables krita karbon braindump author" CAMERAS="ptp2" COLLECTD_PLUGINS="df interface irq load memory rrdtool swap syslog" CPU_FLAGS_X86="aes avx avx2 fma3 mmx mmxext popcnt sse sse2 sse3 sse4_1 sse4_2 ssse3" ELIBC="glibc" GPSD_PROTOCOLS="ashtech aivdm earthmate evermore fv18 garmin garmintxt gpsclock itrax mtk3301 nmea ntrip navcom oceanserver oldstyle oncore rtcm104v2 rtcm104v3 sirf superstar2 timing tsip tripmate tnt ublox ubx" GRUB_PLATFORMS="efi-64" INPUT_DEVICES="keyboard mouse evdev" KERNEL="linux" LCD_DEVICES="bayrad cfontz cfontz633 glk hd44780 lb216 lcdm001 mtxorb ncurses text" LIBREOFFICE_EXTENSIONS="presenter-console presenter-minimizer" LINGUAS="en en_GB de de_AT" OFFICE_IMPLEMENTATION="libreoffice" PHP_TARGETS="php5-5" PYTHON_SINGLE_TARGET="python2_7" PYTHON_TARGETS="python2_7 python3_3 python3_4 python3_5" RUBY_TARGETS="ruby20 ruby21 ruby22 ruby23" USERLAND="GNU" VIDEO_CARDS="intel" XTABLES_ADDONS="quota2 psd pknock lscan length2 ipv4options ipset ipp2p iface geoip fuzzy condition tee tarpit sysrq steal rawnat logmark ipmark dhcpmac delude chaos account"
Unset:  CC, CPPFLAGS, CTARGET, CXX, INSTALL_MASK, LC_ALL, PORTAGE_BUNZIP2_COMMAND, PORTAGE_COMPRESS, PORTAGE_COMPRESS_FLAGS, PORTAGE_RSYNC_EXTRA_OPTS, USE_PYTHON

=================================================================
                        Package Settings
=================================================================

unity-base/unity-7.3.2_p0_p01_p20151016::unity-gentoo was built with the following:
USE="branding -debug -doc -pch -test" ABI_X86="64" PYTHON_TARGETS="python2_7"
```

**Comment by shiznix** [comment] 2016-01-21 08:59
Should be fixed in commit f74b68472ababb8e9a2d5dc62175f4c79c8a98d2

**Comment by and3k** [comment] 2016-01-21 11:47
Now I’m getting a different error: https://gist.githubusercontent.com/and3k/0dedd12c9633aa7aaca2/raw/a6d117c992b73aa4561d4bf2ee225cee09fe53d7/unity-7.3.2_p0_p01_p20151016_build_log_2

**Comment by shiznix** [comment] 2016-01-22 12:50
Looking at the build.log, it looks like you may need to re-emerge 'dev-libs/libsigc++:2'

I've update unity-base/unity ebuild as this was missing from it's DEPEND.

**Comment by and3k** [comment] 2016-01-22 13:42
re-emerging 'dev-libs/libsigc++:2' didn’t help

when I go to the working dir of the ebuild and run make by hand, I get some additional info on the problem (?):

```
[  7%] Built target translations_1
[ 17%] Built target unity-core-6.0
[ 32%] Built target unity-shared
[ 32%] Built target unity-shared-bamf
[ 33%] Built target unity-shared-standalone
[ 33%] Built target app-manager
[ 34%] Built target decorations-style
[ 35%] Built target unity-shared-compiz
[ 40%] Built target previews-lib
[ 47%] Built target dash-lib
[ 48%] Built target dash
[ 48%] Built target app_previews
[ 48%] Built target error_previews
[ 48%] Built target movie_previews
[ 48%] Built target music_previews
[ 48%] Built target payment_previews
[ 48%] Built target social_previews
[ 48%] Building CXX object launcher/CMakeFiles/launcher-lib.dir/LauncherController.cpp.o
/var/tmp/portage/unity-base/unity-7.3.2_p0_p01_p20151016/work/unity-7.3.2+15.10.20151016/launcher/LauncherController.cpp: In constructor ‘unity::launcher::Controller::Impl::Impl(unity::launcher::Controller*, const Ptr&, const Ptr&)’:
/var/tmp/portage/unity-base/unity-7.3.2_p0_p01_p20151016/work/unity-7.3.2+15.10.20151016/launcher/LauncherController.cpp:153:38: error: ‘group’ is not a member of ‘sigc’
   wm.viewport_layout_changed.connect(sigc::group(sigc::mem_fun(this, &Controller::Impl::UpdateNumWorkspaces), sigc::_1 * sigc::_2));
                                      ^
/var/tmp/portage/unity-base/unity-7.3.2_p0_p01_p20151016/work/unity-7.3.2+15.10.20151016/launcher/LauncherController.cpp:153:111: error: ‘_1’ is not a member of ‘sigc’
   wm.viewport_layout_changed.connect(sigc::group(sigc::mem_fun(this, &Controller::Impl::UpdateNumWorkspaces), sigc::_1 * sigc::_2));
                                                                                                               ^
/var/tmp/portage/unity-base/unity-7.3.2_p0_p01_p20151016/work/unity-7.3.2+15.10.20151016/launcher/LauncherController.cpp:153:111: note: suggested alternatives:
In file included from /usr/include/boost/numeric/conversion/converter_policies.hpp:18:0,
                 from /usr/include/boost/numeric/conversion/converter.hpp:14,
                 from /usr/include/boost/numeric/conversion/cast.hpp:33,
                 from /usr/include/boost/lexical_cast.hpp:159,
                 from /usr/include/Nux-4.0/NuxCore/PropertyTraits.h:31,
                 from /usr/include/Nux-4.0/NuxCore/Property.h:25,
                 from /usr/include/Nux-4.0/NuxCore/Object.h:33,
                 from /usr/include/Nux-4.0/NuxCore/NuxCore.h:730,
                 from /usr/include/Nux-4.0/Nux/Nux.h:26,
                 from /var/tmp/portage/unity-base/unity-7.3.2_p0_p01_p20151016/work/unity-7.3.2+15.10.20151016/launcher/LauncherController.cpp:25:
/usr/lib/gcc/x86_64-pc-linux-gnu/5.3.0/include/g++-v5/functional:782:34: note:   ‘std::placeholders::_1’
     extern const _Placeholder<1> _1;
                                  ^
In file included from /usr/include/boost/mpl/aux_/include_preprocessed.hpp:37:0,
                 from /usr/include/boost/mpl/placeholders.hpp:43,
                 from /usr/include/boost/mpl/apply.hpp:24,
                 from /usr/include/boost/mpl/aux_/iter_apply.hpp:17,
                 from /usr/include/boost/mpl/aux_/find_if_pred.hpp:14,
                 from /usr/include/boost/mpl/find_if.hpp:17,
                 from /usr/include/boost/mpl/find.hpp:17,
                 from /usr/include/boost/mpl/aux_/contains_impl.hpp:20,
                 from /usr/include/boost/mpl/contains.hpp:20,
                 from /usr/include/boost/math/policies/policy.hpp:10,
                 from /usr/include/boost/math/special_functions/math_fwd.hpp:28,
                 from /usr/include/boost/math/special_functions/sign.hpp:17,
                 from /usr/include/boost/lexical_cast.hpp:167,
                 from /usr/include/Nux-4.0/NuxCore/PropertyTraits.h:31,
                 from /usr/include/Nux-4.0/NuxCore/Property.h:25,
                 from /usr/include/Nux-4.0/NuxCore/Object.h:33,
                 from /usr/include/Nux-4.0/NuxCore/NuxCore.h:730,
                 from /usr/include/Nux-4.0/Nux/Nux.h:26,
                 from /var/tmp/portage/unity-base/unity-7.3.2_p0_p01_p20151016/work/unity-7.3.2+15.10.20151016/launcher/LauncherController.cpp:25:
/usr/include/boost/mpl/aux_/preprocessed/gcc/placeholders.hpp:29:16: note:   ‘mpl_::_1’
 typedef arg<1> _1;
                ^
/usr/include/boost/mpl/aux_/preprocessed/gcc/placeholders.hpp:29:16: note:   ‘mpl_::_1’
/usr/include/boost/mpl/aux_/preprocessed/gcc/placeholders.hpp:29:16: note:   ‘mpl_::_1’
/var/tmp/portage/unity-base/unity-7.3.2_p0_p01_p20151016/work/unity-7.3.2+15.10.20151016/launcher/LauncherController.cpp:153:122: error: ‘_2’ is not a member of ‘sigc’
   wm.viewport_layout_changed.connect(sigc::group(sigc::mem_fun(this, &Controller::Impl::UpdateNumWorkspaces), sigc::_1 * sigc::_2));
                                                                                                                          ^
/var/tmp/portage/unity-base/unity-7.3.2_p0_p01_p20151016/work/unity-7.3.2+15.10.20151016/launcher/LauncherController.cpp:153:122: note: suggested alternatives:
In file included from /usr/include/boost/numeric/conversion/converter_policies.hpp:18:0,
                 from /usr/include/boost/numeric/conversion/converter.hpp:14,
                 from /usr/include/boost/numeric/conversion/cast.hpp:33,
                 from /usr/include/boost/lexical_cast.hpp:159,
                 from /usr/include/Nux-4.0/NuxCore/PropertyTraits.h:31,
                 from /usr/include/Nux-4.0/NuxCore/Property.h:25,
                 from /usr/include/Nux-4.0/NuxCore/Object.h:33,
                 from /usr/include/Nux-4.0/NuxCore/NuxCore.h:730,
                 from /usr/include/Nux-4.0/Nux/Nux.h:26,
                 from /var/tmp/portage/unity-base/unity-7.3.2_p0_p01_p20151016/work/unity-7.3.2+15.10.20151016/launcher/LauncherController.cpp:25:
/usr/lib/gcc/x86_64-pc-linux-gnu/5.3.0/include/g++-v5/functional:783:34: note:   ‘std::placeholders::_2’
     extern const _Placeholder<2> _2;
                                  ^
In file included from /usr/include/boost/mpl/aux_/include_preprocessed.hpp:37:0,
                 from /usr/include/boost/mpl/placeholders.hpp:43,
                 from /usr/include/boost/mpl/apply.hpp:24,
                 from /usr/include/boost/mpl/aux_/iter_apply.hpp:17,
                 from /usr/include/boost/mpl/aux_/find_if_pred.hpp:14,
                 from /usr/include/boost/mpl/find_if.hpp:17,
                 from /usr/include/boost/mpl/find.hpp:17,
                 from /usr/include/boost/mpl/aux_/contains_impl.hpp:20,
                 from /usr/include/boost/mpl/contains.hpp:20,
                 from /usr/include/boost/math/policies/policy.hpp:10,
                 from /usr/include/boost/math/special_functions/math_fwd.hpp:28,
                 from /usr/include/boost/math/special_functions/sign.hpp:17,
                 from /usr/include/boost/lexical_cast.hpp:167,
                 from /usr/include/Nux-4.0/NuxCore/PropertyTraits.h:31,
                 from /usr/include/Nux-4.0/NuxCore/Property.h:25,
                 from /usr/include/Nux-4.0/NuxCore/Object.h:33,
                 from /usr/include/Nux-4.0/NuxCore/NuxCore.h:730,
                 from /usr/include/Nux-4.0/Nux/Nux.h:26,
                 from /var/tmp/portage/unity-base/unity-7.3.2_p0_p01_p20151016/work/unity-7.3.2+15.10.20151016/launcher/LauncherController.cpp:25:
/usr/include/boost/mpl/aux_/preprocessed/gcc/placeholders.hpp:42:16: note:   ‘mpl_::_2’
 typedef arg<2> _2;
                ^
/usr/include/boost/mpl/aux_/preprocessed/gcc/placeholders.hpp:42:16: note:   ‘mpl_::_2’
/usr/include/boost/mpl/aux_/preprocessed/gcc/placeholders.hpp:42:16: note:   ‘mpl_::_2’
launcher/CMakeFiles/launcher-lib.dir/build.make:494: recipe for target 'launcher/CMakeFiles/launcher-lib.dir/LauncherController.cpp.o' failed
make[2]: *** [launcher/CMakeFiles/launcher-lib.dir/LauncherController.cpp.o] Error 1
CMakeFiles/Makefile2:1023: recipe for target 'launcher/CMakeFiles/launcher-lib.dir/all' failed
make[1]: *** [launcher/CMakeFiles/launcher-lib.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2
```

I already remerged boost and nux, that didn’t help…

**Comment by shiznix** [comment] 2016-01-22 22:58
Finally reproduced this by installing the unstable keyword masked version dev-libs/libsigc++-2.6.2.

Will commit something shortly to mask >=libsigc++-2.6* but in the meantime unity should be ok once you downgrade back to libsigc++-2.4

**Comment by and3k** [comment] 2016-01-23 13:30
I downgraded to libsigc++-2.4, now I get this error:

```
# make
[  7%] Built target translations_1
[ 17%] Built target unity-core-6.0
[ 32%] Built target unity-shared
[ 32%] Built target unity-shared-bamf
[ 33%] Built target unity-shared-standalone
[ 33%] Linking CXX executable app-manager
/usr/lib/libnux-core-4.0.so: undefined reference to `sigc::slot_base::slot_base(sigc::slot_base&&)'
collect2: error: ld returned 1 exit status
unity-shared/CMakeFiles/app-manager.dir/build.make:99: recipe for target 'unity-shared/app-manager' failed
make[2]: *** [unity-shared/app-manager] Error 1
CMakeFiles/Makefile2:327: recipe for target 'unity-shared/CMakeFiles/app-manager.dir/all' failed
make[1]: *** [unity-shared/CMakeFiles/app-manager.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by and3k** [comment] 2016-01-23 13:39
sorry, had to rebuild nux, now it worked!

**Comment by and3k** [comment] 2016-01-23 13:41
FYI, this are the masks to get downgraded to libsigc++-2.4 in ~amd64:

```
=dev-libs/libsigc++-2.6*
=dev-cpp/glibmm-2.46*
=dev-cpp/pangomm-2.38*
=dev-cpp/cairomm-1.12*
=dev-cpp/atkmm-2.24*
```

**Comment by shiznix** [comment] 2016-01-23 20:18
Excellent, closing this one then.

**Closed by shiznix** 2016-01-23 20:18 UTC
