### ISSUE TITLE
compile of 'dev-cpp/gtest-1.8.1_p_p_p3' fails

### ISSUE THREAD

**Issue by renegart** [shiznix/unity-gentoo#229] opened 2020-01-10 07:35 UTC
`
* Package 'dev-cpp/gtest-1.8.1_p_p_p3' has one or more collisions
 * between symlinks and directories, which is explicitly forbidden by PMS
 * section 13.4 (see bug #326685):
 * 
 *      /usr/src/gmock
 *      /usr/src/gtest
 * 
 * This package will overwrite one or more files that may belong to other
 * packages (see list below).
 * 
 * Detected file collision(s):
 * 
 *      /usr/src/gmock
 *      /usr/src/gtest
 * 
 * Searching all installed packages for file collisions...
 * 
 * Press Ctrl-C to Stop
 * 
 * dev-cpp/gtest-1.7.0_p_p4_p01:0::unity-gentoo
 *      /usr/src/gtest
 * 
 * dev-cpp/gmock-1.7.0_p18092013_p_p0201:0::unity-gentoo
 *      /usr/src/gmock
 * 
 * Package 'dev-cpp/gtest-1.8.1_p_p_p3' NOT merged since it has one or
 * more collisions between symlinks and directories, which is explicitly
 * forbidden by PMS section 13.4 (see bug #326685). If necessary, refer
 * to your elog messages for the whole content of the above message.
`

**Comment by c4pp4** [comment] 2020-01-10 18:53
emerge -C gmock gtest
emerge 1 gtest

**Comment by shiznix** [comment] 2020-01-10 22:02
WRT /usr/src/gtest collision, portage dev's implementation to fix bug #326685 is incomplete.
The exact same symlink provided by the same package should not trigger a collision detect on a version bump, this is a regression.

/usr/src/gmock collision shouldn't happen either because it's old package (dev-cpp/gmock) has been soft blocked in dev-cpp/gtest.

I feel both cases could be easily fixed if portage just treated installed files/symlinks/fifos objects all the same.

**Comment by shiznix** [comment] 2020-01-10 22:16
Should be fixed in commit 3aa61172cdca4d5a64a5845199a756bdd8861f0c - thanks :)

**Closed by shiznix** 2020-01-10 22:16 UTC
